root: true
env:
  browser: true
  node: true
  es2021: true
settings:
  react:
    version: detect
extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    plugins:  
      - '@typescript-eslint'
    extends:
      - plugin:@typescript-eslint/recommended
    parser: '@typescript-eslint/parser'
